---
version: '2.3'

services:

  # HTTPD Server
  httpd:
    image: johnea/webserver:${HTTPD_SERVER:-nginx-stable}
    build:
      context: ../../Dockerfiles
      dockerfile: Dockerfile-${DOCKER_FILE:-nginx-stable.alpine}
    hostname: httpd
    environment:
      - NEW_UID=1000
      - NEW_GID=1000
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/default/htdocs
